### ISSUE TITLE
Windows平台上问题汇总

### ISSUE THREAD

**Issue by zavatar** [leeyeh/leantodo-react-native#1]
大家知道react-native对Windows平台的支持不是特别积极，在搭建本demo期间遇到的几个问题分享出来，以供探讨。avoscloud: 1.0.0-rc5, react-native: 0.13.2
1. Watcher took too long to load 问题解决方案见 https://github.com/facebook/react-native/issues/2841
2. react-native Packager不兼容Windows路径，导致package.json里的browser配置无效，以至于报错各种包require不到。解决方案见 `node_modules\react-native\packager\react-packager\src\DependencyResolver\Package.js` 的patch
   [Package.js.txt](https://github.com/leancloud/leantodo-react-native/files/47144/Package.js.txt)
3. classnames 包没有配置依赖。`npm install classnames` 装一下即可。

**Comment by leeyeh** [comment]
3 是我们疏忽了，1、2 是 React Native 的 issue，感谢分享经验。
